library(dplyr)
library(tidyverse)
df<-read.csv('MechaCar_mpg.csv')
df_lm<-lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,data=df)
summary(df_lm)
susdf<-read.csv('Suspension_Coil.csv')
fullsummary <- susdf %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),Std=sd(PSI))
lotsummary <- susdf %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),Std=sd(PSI),.groups = 'keep' )
t.test(susdf$PSI,mu=1500)
t.test(subset(susdf,Manufacturing_Lot=='Lot1')$PSI,mu=1500)
t.test(subset(susdf,Manufacturing_Lot=='Lot2')$PSI,mu=1500)
t.test(subset(susdf,Manufacturing_Lot=='Lot3')$PSI,mu=1500)
